trigger:
- main

pool:
  name: 'mypool'

variables:
  imageName: 'petclinic-app'

steps:
- script: |
    # Install Java 17 using package manager (Ubuntu/Debian)
    sudo apt-get update
    sudo apt-get install -y openjdk-17-jdk
    echo "##vso[task.setvariable variable=JAVA_HOME]$(readlink -f /usr/bin/java | sed 's:/bin/java::')"
    java -version
  displayName: 'Install Java 17'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package -DskipTests'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    mavenOptions: '-Xmx1024m'

- task: Docker@2
  inputs:
    containerRegistry: 'acr-docker-conn'
    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      latest
      $(Build.BuildId)
