trigger:
- main

pool:
  name: 'mypool'

variables:
  imageName: 'petclinic-app'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    javaHomeOption: 'Path'
    jdkDirectory: '$(JAVA_HOME_11_X64)'
    mavenOptions: '-Xmx1024m'

- task: Docker@2
  inputs:
    containerRegistry: 'acr-docker-conn'
    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      latest
      $(Build.BuildId)
