trigger:
- main

pool:
  name: 'mypool'

variables:
  imageName: 'petclinic-app'

steps:
# Set JAVA_HOME manually for Java 17
- script: |
    echo "##vso[task.setvariable variable=JAVA_HOME_17_X64]/usr/lib/jvm/java-17-openjdk-amd64"
  displayName: 'Set JAVA_HOME_17_X64'

# Run Maven build using Maven@1
- task: Maven@1
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
  displayName: 'Build with Maven'

# Docker Build & Push
- task: Docker@2
  inputs:
    containerRegistry: 'acr-docker-conn'  # 🔁 Make sure this is a **Docker Registry** type
    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      latest
      $(Build.BuildId)
  displayName: 'Build & Push Docker image'
