trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'petclinic-app'

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    mavenOptions: '-Xmx1024m'

- task: Docker@2
  inputs:
    containerRegistry: 'acr-docker-conn'
    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      latest
      $(Build.BuildId)
