trigger:
- main

pool:  
  name: 'mypool'

variables:
  imageName: 'petclinic-app'


steps:

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    mavenOptions: '-Xmx1024m'

- task: Docker@2
  inputs:
    containerRegistry: 'petapp-acr-conn'
    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      latest
      $(Build.BuildId)

