trigger:
- main

pool:
  name: 'mypool' 

variables:
- group: acr-secrets  # registry-username and registry-password should be defined here

stages:
- stage: Deploy
  jobs:
  - job: DeployToACI
    displayName: 'Deploy to Azure Container Instance'
    steps:
    - task: AzureCLI@2
      displayName: 'Deploy ACI via Azure CLI'
      inputs:
        azureSubscription: 'azure-coffeejunkie-service-conn'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Deleting existing container instance..."
          az container delete \
            --name my-app-container \
            --resource-group my-resource-group \
            --yes || true

          echo "Creating new container instance with custom CPU and memory..."
          az container create \
            --resource-group my-resource-group \
            --name my-app-container \
            --image myregistry.azurecr.io/my-app:latest \
            --cpu 2 \
            --memory 3 \
            --dns-name-label my-app-dns-name \
            --ports 8080 \
            --registry-login-server myregistry.azurecr.io \
            --registry-username $(registry-username) \
            --registry-password $(registry-password)
