trigger:
- main

pool:
  name: 'mypool'  # Your self-hosted agent pool

variables:
- group: acr-secrets  # Securely injected ACR credentials

stages:
- stage: Deploy
  jobs:
  - job: DeployToACI
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'azure-coffeejunkie-service-conn'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az container create \
            --resource-group coffeejunkie-rg \
            --name my-app \
            --image coffeejunkieacr.azurecr.io/petclinic-app:latest \
            --registry-login-server coffeejunkieacr.azurecr.io \
            --registry-username $(ACR_USERNAME) \
            --registry-password $(ACR_PASSWORD) \
            --cpu 1 \
            --memory 1 \
            --dns-name-label coffeejunkie-app \
            --ports 8080
      displayName: 'Deploy to Azure Container Instance'
