trigger:
- main

pool:
  name: 'mypool' 

stages:
- stage: Deploy
  jobs:
  - job: DeployToACI
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'azure-coffeejunkie-service-conn'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          inlineScript: |
           # Deploy container to ACI
           az container create \
             --resource-group coffeejunkie-rg \
             --name coffeejunkie \
             --image coffeejunkieacr.azurecr.io/coffeejunkie-app:v1 \
             --registry-login-server coffeejunkieacr.azurecr.io \
             --registry-username $(ACR_USERNAME) \
             --registry-password $(ACR_PASSWORD) \
             --cpu 1 \
             --memory 1 \
             --dns-name-label coffeejunkie-app \
             --ports 8080

      displayName: 'Deploy to Azure Container Instance'
      env:
        ACR_USERNAME: $(ACR_USERNAME)
        ACR_PASSWORD: $(ACR_PASSWORD)

variables:
- group: acr-secrets  
